export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_TOKEN = "CLEAR_TOKEN";

export const GET_TOKEN_COMPLETED = "GET_TOKEN_COMPLETED";
export const GET_TOKEN_ERROR = "GET_TOKEN_ERROR";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";
export const GET_TOKEN_START = "GET_TOKEN_START";

export const LIVENESS_PROBE = "LIVENESS_PROBE";
