export const GET_INDEX_COMPLETED = "FETCH_INDEX_COMPLETED";
export const GET_INDEX_ERROR = "FETCH_INDEX_ERROR";
export const GET_INDEX_START = "FETCH_INDEX_START";
export const GET_INDEX_SUCCESSFUL = "FETCH_INDEX_SUCCESSFUL";

export const POST_ARTICLE_COMPLETED = " POST_ARTICLE_COMPLETED";
export const POST_ARTICLE_ERROR = " POST_ARTICLE_ERROR";
export const POST_ARTICLE_START = " POST_ARTICLE_START";
export const POST_ARTICLE_SUCCESSFUL = " POST_ARTICLE_SUCCESSFUL";

export const PUT_INDEX_COMPLETED = "UPDATE_INDEX_COMPLETED";
export const PUT_INDEX_ERROR = "UPDATE_INDEX_ERROR";
export const PUT_INDEX_START = "UPDATE_INDEX_START";
export const PUT_INDEX_SUCCESSFUL = "UPDATE_INDEX_SUCCESSFUL";
