export const POST_ARTICLE_UPLOAD = 'START_ARTICLE_UPLOAD';
export const SUCCESS_ARTICLE_UPLOAD = 'SUCCESS_ARTICLE_UPLOAD';
export const WAIT_ARTICLE_UPLOAD = 'WAIT_ARTICLE_UPLOAD';

export const START_UPLOAD_ARTICLE_POST_REQUEST = 'START_UPLOAD_ARTICLE_POST_REQUEST';
export const END_UPLOAD_ARTICLE_POST_REQUEST = 'END_UPLOAD_ARTICLE_POST_REQUEST';

export const UPDATE_INDEX_COMPLETED = 'UPDATE_INDEX_COMPLETED';
export const UPDATE_INDEX_ERROR = 'UPDATE_INDEX_ERROR';
export const UPDATE_INDEX_START = 'UPDATE_INDEX_START';
export const UPDATE_INDEX_SUCCESSFUL = 'UPDATE_INDEX_SUCCESSFUL';
