export const CLEAR_EDIT_NOTE = "CLEAR_EDIT_NOTE";

export const GET_EDIT_NOTE_COMPLETED = "GET_EDIT_NOTE_COMPLETED";
export const GET_EDIT_NOTE_ERROR = "GET_EDIT_NOTE_ERROR";
export const GET_EDIT_NOTE_START = "GET_EDIT_NOTE_START";
export const GET_EDIT_NOTE_SUCCESSFUL = "GET_EDIT_NOTE_SUCCESSFUL";

export const GET_INDEX_COMPLETED = "GET_INDEX_COMPLETED";
export const GET_INDEX_ERROR = "GET_INDEX_ERROR";
export const GET_INDEX_START = "GET_INDEX_START";
export const GET_INDEX_SUCCESSFUL = "GET_INDEX_SUCCESSFUL";

export const UPSERT_INDEX_COMPLETED = "UPSERT_INDEX_COMPLETED";
export const UPSERT_INDEX_ERROR = "UPSERT_INDEX_ERROR";
export const UPSERT_INDEX_START = "UPSERT_INDEX_START";
export const UPSERT_INDEX_SUCCESSFUL = "UPSERT_INDEX_SUCCESSFUL";

export const UPSERT_NOTE_COMPLETED = " UPSERT_NOTE_COMPLETED";
export const UPSERT_NOTE_ERROR = " UPSERT_NOTE_ERROR";
export const UPSERT_NOTE_START = " UPSERT_NOTE_START";
export const UPSERT_NOTE_SUCCESSFUL = " UPSERT_NOTE_SUCCESSFUL";
