export const END_ARTICLE_LIST_GET_REQUEST = "END_ARTICLE_LIST_GET_REQUEST";
export const FAILED_ARTICLE_LIST_GET_REQUEST =
  "FAILED_ARTICLE_LIST_GET_REQUEST";
export const START_ARTICLE_LIST_GET_REQUEST = "START_ARTICLE_LIST_GET_REQUEST";
export const SUCCESSFUL_ARTICLE_LIST_GET_REQUEST =
  "SUCCESSFUL_ARTICLE_LIST_GET_REQUEST";

export const END_SINGLE_ARTICLE_GET_REQUEST = "END_SINGLE_ARTICLE_GET_REQUEST";
export const FAILED_SINGLE_ARTICLE_GET_REQUEST =
  "FAILED_SINGLE_ARTICLE_GET_REQUEST";
export const SUCCESSFUL_SINGLE_ARTICLE_GET_REQUEST =
  "SUCCESSFUL_SINGLE_ARTICLE_GET_REQUEST";

export const SUCCESSFUL_ARTICLES_GET_REQUEST =
  "SUCCESSFUL_ARTICLES_GET_REQUEST";
