export const END_ARTICLE_LIST_GET_REQUEST = "END_ARTICLE_LIST_GET_REQUEST";
export const FAILED_ARTICLE_LIST_GET_REQUEST =
  "FAILED_ARTICLE_LIST_GET_REQUEST";
export const START_ARTICLE_LIST_GET_REQUEST = "START_ARTICLE_LIST_GET_REQUEST";
export const SUCCESSFUL_ARTICLE_LIST_GET_REQUEST =
  "SUCCESSFUL_ARTICLE_LIST_GET_REQUEST";

export const END_SINGLE_ARTICLE_GET_REQUEST = "END_SINGLE_ARTICLE_GET_REQUEST";
export const FAILED_SINGLE_ARTICLE_GET_REQUEST =
  "FAILED_SINGLE_ARTICLE_GET_REQUEST";
export const SUCCESSFUL_SINGLE_ARTICLE_GET_REQUEST =
  "SUCCESSFUL_SINGLE_ARTICLE_GET_REQUEST";

export const SUCCESSFUL_ARTICLES_GET_REQUEST =
  "SUCCESSFUL_ARTICLES_GET_REQUEST";

// possible future types
export const CLEAR_ARTICLE_ERRORS = "CLEAR_ARTICLE_ERRORS";

export const GET_ARTICLES_LIST_COMPLETED = "GET_ARTICLES_LIST_COMPLETED";
export const GET_ARTICLES_LIST_ERROR = "GET_ARTICLES_LIST_ERROR";
export const GET_ARTICLES_LIST_SUCCESS = "GET_ARTICLES_LIST_SUCCESS";
export const GET_ARTICLES_LIST_START = "GET_ARTICLES_LIST_START";

export const GET_MULTI_ARTICLES_COMPLETED = "GET_MULTI_ARTICLES_COMPLETED";
export const GET_MULTI_ARTICLES_ERROR = "GET_MULTI_ARTICLES_ERROR";
export const GET_MULTI_ARTICLES_SUCCESS = "GET_MULTI_ARTICLES_SUCCESS";
export const GET_MULTI_ARTICLES_START = "GET_MULTI_ARTICLES_START";

export const GET_SINGLE_ARTICLE_COMPLETED = "GET_SINGLE_ARTICLE_COMPLETED";
export const GET_SINGLE_ARTICLE_ERROR = "GET_SINGLE_ARTICLE_ERROR";
export const GET_SINGLE_ARTICLE_SUCCESS = "GET_SINGLE_ARTICLE_SUCCESS";
export const GET_SINGLE_ARTICLE_START = "GET_SINGLE_ARTICLE_START";
