export const GET_NOTES_ALL_COMPLETED = "GET_NOTES_ALL_COMPLETED";
export const GET_NOTES_ALL_ERROR = "GET_NOTES_ALL_ERROR";
export const GET_NOTES_ALL_START = "GET_NOTES_ALL_START";
export const GET_NOTES_ALL_SUCCESS = "GET_NOTES_ALL_SUCCESS";

export const GET_NOTE_INDEX_COMPLETED = "GET_NOTE_INDEX_COMPLETED";
export const GET_NOTE_INDEX_ERROR = "GET_NOTE_INDEX_ERROR";
export const GET_NOTE_INDEX_START = "GET_NOTE_INDEX_START";
export const GET_NOTE_INDEX_SUCCESS = "GET_NOTE_INDEX_SUCCESS";
